---
# l3ls fabric values - update these values with caution,
# some changes could be disruptive.

fabric_name: fabric

# update p2p mtu 9000 -> 1500
p2p_uplinks_mtu: '{{default_mtu_link}}'

# enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# vpn import prunning
evpn_import_prunning: true

# enable route target membership constraint address family on evpn overlay bgp peerings (min. eos 4.25.1f)
# requires use ebgp as overlay protocol.
evpn_overlay_bgp_rtc: false

# bgp peer groups passwords
bgp_peer_groups:
  ipv4_underlay_peers:
    password: "aqqvkeimxju+ugq/yyvv9w=="
  evpn_overlay_peers:
    password: "q+vnvip5i4rvjw1cxfv2wa=="
  mlag_ipv4_underlay_peer:
    password: "vneag8gmeqf3d3cn6pktxq=="

# enable route target membership constraint
# evpn_overlay_bgp_rtc: true
