---
scenario:
  converge_sequence:
    - syntax
    - create
    - converge
  test_sequence:
    - syntax
    - converge
    - idempotence
  cleanup_sequence:
    - destroy

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: default
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    managed: false
    groups:
      - all

provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_extensions: 'jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n'
      gathering: explicit
    inventory:
      enable_plugins: yaml
  inventory:
    links:
      hosts: 'inventory/inventory.yml'
      host_vars: 'inventory/host_vars/'
      group_vars: 'inventory/group_vars/'
  ansible_args:
    - --inventory=inventory/inventory.yml

verifier:
  name: ansible
  inventory:
    links:
      hosts: 'inventory/inventory.yml'
      host_vars: 'inventory/host_vars/'
      group_vars: 'inventory/group_vars/'
  ansible_args:
    - --inventory=inventory/inventory.yml
  config_options:
    defaults:
      jinja2_extensions: 'jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n'
      gathering: explicit
    inventory:
      enable_plugins: yaml