port_profiles:
  all:
    mode: trunk
    vlans: "1-4000"
  a-pr01-dmz:
    mode: access
    vlans: "110"
  a-pr01-trust:
    mode: access
    vlans: "111"
  b-elan-201:
    mode: access
    vlans: "201"
  storm_control_unused:
    mode: trunk
    vlans: "1-4000"
    storm_control:
      all:
        level: 10
        unit: percent
      broadcast:
        level: 100
        unit: pps
      multicast:
        level: 1
        unit: percent
      'unknown-unicast':
        level: 2
        unit: percent