---
# defaults file for avd_to_containerlab

# cEOS Image to use
ceos_lab_version: ceos:latest

# Default management network IP
mgmt_network_v4: 192.168.1.0/24

# Default containerlabs configuration file generated
containerlab_configuration: '{{ inventory_dir }}/containerlabs.yml'
